name: Build and push iovisor/bcc ubuntu 22.04
on:
  workflow_dispatch:
    inputs:
      ghcr_org:
        type: string
        required: false
        default: flatcar
        description: |
          The name of the GitHub org where the docker images should be pushed.

permissions:
  contents: read

jobs:
  build_and_push:
    permissions:
      packages: write
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: ader1990/bcc
        ref: fix_debian_changelog
        fetch-depth: 0
        fetch-tags: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry (ghcr)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.ubuntu
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ghcr.io/${{ inputs.ghcr_org }}/bcc:latest
