name: Build and push iovisor/bcc ubuntu 22.04
on:
  workflow_dispatch:
    inputs:
      ghcr_org:
        type: string
        required: false
        default: flatcar
        description: |
          The name of the GitHub org where the docker images should be pushed.

permissions:
  contents: read

jobs:
  build_and_push:
    permissions:
      packages: write
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: iovisor/bcc
        ref: master
        fetch-depth: 0
        fetch-tags: true
    - name: check_dir
      shell: bash
      run: |
        # https://github.com/iovisor/bcc/issues/4842
        # Debian changelog for v0.29.1 is not yet updated and the build fails.
        echo -e "bcc (0.29.1-1) unstable; urgency=low\n\n  * fix debian build\n\n -- Adrian Vladu <avladu@cloudbasesolutions.com>  Thu, 6 Dec 2024 17:00:00 +0000\n\n$(cat debian/changelog)" > debian/changelog
        # Github action env builds the Py3 libs in /usr/lib
        echo 'usr/lib/python3*' > debian/python-bcc.install
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GitHub Container Registry (ghcr)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.ubuntu
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ inputs.ghcr_org }}/bcc:latest
